version: "3.6"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    networks:
      - reactd3appnet
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  reactd3appclient:
    build:
      context: .
      dockerfile: dockerfiles/client_dockerfile
      args:
        appid: appid
        backendurl: http://backendurl
    networks:
      - reactd3appnet
    environment:
      - VIRTUAL_HOST=reactd3client

  reactd3appbackend:
    build:
      context: .
      dockerfile: dockerfiles/backend_dockerfile
    networks:
      - reactd3appnet
    environment:
      - APPLICATION_ID=appid
      - APPLICATION_SECRET=appsecret
      - CLIENT_URL=http://clienturl
      - VIRTUAL_HOST=reactd3server

networks:
  reactd3appnet:
    driver: bridge