version: '3.4'

services:
  reactd3webappbackend:
    image: reactd3webappbackend
    build:
      context: src/server
      dockerfile: ./Dockerfile
    environment:
      APPLICATION_ID: application_id
      APPLICATION_SECRET: application_secret
      CLIENT_URL: http://localhost:8000
      NODE_ENV: production
    ports:
      - 9000:9000

  reactd3webappclient:
    image: reactd3webappclient
    build:
      context: src/client
      dockerfile: ./Dockerfile
      args:
        application_id: application_id
        node_env: production
        server_url: http://localhost:9000
    ports:
      - 8000:80
