version: '3.4'

services:
  reactd3webappbackend:
    image: reactd3webappbackend
    build:
      context: src/server
      dockerfile: ./Dockerfile
    environment:
      APPLICATION_ID: application_id
      APPLICATION_SECRET: application_secret
      CLIENT_URL: http://localhost:8000
      NODE_ENV: development
    ports:
      - 9000:9000
      - 9230:9230
    command: ["node", "--inspect=0.0.0.0:9230", "index.js"]

  reactd3webappclient:
    image: reactd3webappclient
    build:
      context: src/client
      dockerfile: ./Dockerfile-debug
    environment:
      APPLICATION_ID: application_id
      NODE_ENV: development
      SERVER_URL: http://localhost:9000
    ports:
      - 8000:8000
      - 9231:9231
    command: ["node", "--inspect=0.0.0.0:9231", "run.js", "dev"]
