version: "3.8"

name: reactd3webapp_apidebug_compose

services:
  api:
    container_name: reactd3webapp_api
    build:
      context: src/api
      dockerfile: Dockerfile
      tags:
        - rolspace/reactd3webapp_api:debug
    environment:
      NODE_ENV: development
    env_file:
      - src/api/.env
    ports:
      - 9000:9000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "run.js"]
