version: '3.8'

name: reactd3webapp_api_compose

services:
  api:
    container_name: reactd3webapp_api
    build:
      context: src/api
      dockerfile: Dockerfile
      tags:
        - rolspace/reactd3webapp_api:latest
    environment:
      NODE_ENV: production
    env_file:
      - src/api/.env
    ports:
      - 9000:9000
