sonar.organization=rolspace
sonar.projectKey=rolspace_react-d3-webapp
sonar.coverage.exclusions=**/__tests__/**,**/index.ts,**/main.tsx,**/run.ts,**/vitest.config.*,**/webpack/**,**/testUtils.tsx,**/types/**
sonar.javascript.lcov.reportPaths=**/lcov.info
sonar.sources=src
sonar.verbose=true
