version: "3.6"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    networks:
      - reactd3appnet
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  reactd3appclient:
    image: reactd3appclient
    networks:
      - reactd3appnet
    environment:
      - VIRTUAL_HOST=reactd3client

  reactd3appbackend:
    image: reactd3appbackend
    networks:
      - reactd3appnet
    environment:
      - CLIENT_DOMAIN=http://reactd3client
      - GITHUB_TOKEN=somevalidgithubtoken
      - GITHUB_USER=someuser
      - VIRTUAL_HOST=reactd3backend

networks:
  reactd3appnet:
    driver: bridge