FROM node:lts-alpine

ENV APPLICATION_ID=12345abcde
ENV NODE_ENV=development
ENV SERVER_URL=http://serverurl

WORKDIR /usr/src/app
COPY . .
RUN cd public && rm -rf ./dist && cd /usr/src/app \
    && chown -R node /usr/src/app
USER node
RUN npm install --silent
EXPOSE 8000
CMD ["node", "run.js", "dev"]
