name: build

on: [push, workflow_call]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build-react:
        name: Build React application
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: ${{ vars.NODE_VERSION }}
            cache: 'yarn'
            cache-dependency-path: 'yarn.lock'

        - name: Build
          run: |
            cd src/client
            yarn --immutable
            yarn build
