name: build

on: [push, workflow_dispatch]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-test-build-react:
    name: Lint, test, build React application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Lint and Test
        run: |
          cd src/client
          yarn --immutable && yarn lint && yarn test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: client-coverage
          path: ./src/client/coverage/

      - name: Build
        run: |
          cd src/client
          yarn build

  lint-test-node:
    name: Lint, test Node application
    runs-on: ubuntu-latest
    needs: lint-test-build-react

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Lint and Test
        run: |
          cd src/server
          yarn --immutable && yarn lint && yarn test --coverage

      - name: Download client coverage
        uses: actions/download-artifact@v3
        with:
          name: client-coverage
          path: ./src/client/coverage/

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=rolspace
            -Dsonar.projectKey=rolspace_react-d3-webapp
            -Dsonar.javascript.lcov.reportPaths=**/lcov.info
            -Dsonar.sources=.
            -Dsonar.coverage.exclusions=**/__tests__/**,**/index.js,**/main.js,**/run.js,**/jest.config.*,**/webpack*.js,**/testUtils.jsx
            -Dsonar.verbose=true

