name: ci
run-name: Run CI process

on: [push]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-test-build-client:
    name: Lint, test, build React client application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Lint and Test
        run: |
          cd src/client
          yarn --immutable && yarn lint && yarn test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: ./src/client/coverage/

      - name: Build
        run: |
          cd src/client
          yarn build

  lint-test-api:
    name: Lint, test Node API application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Lint and Test
        run: |
          cd src/api
          yarn --immutable && yarn lint && yarn test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: ./src/api/coverage/

  sonar:
    name: Perform Sonar analysis
    runs-on: ubuntu-latest
    needs: [lint-test-build-client, lint-test-api]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current version
        id: version
        run: |
          echo "value=$(npm pkg get version --workspaces=false | tr -d \")" >> "$GITHUB_OUTPUT"

      - name: Get current commit
        id: commit
        run: |
          echo "value=$(echo ${{ github.sha }} | sed 's/\(.\{7\}\).*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Download client coverage
        uses: actions/download-artifact@v4
        with:
          name: client-coverage
          path: ./src/client/coverage/

      - name: Download API coverage
        uses: actions/download-artifact@v4
        with:
          name: api-coverage
          path: ./src/api/coverage/

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectVersion=${{ steps.version.outputs.value }}-${{ steps.commit.outputs.value }}
