name: ci
run-name: Run CI

on: [push]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci-client:
    name: Run CI for the React client application
    defaults:
      run:
        working-directory: ./src/client
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: yarn install
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Test with coverage
        run: yarn test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: client-coverage
          path: ./src/client/coverage/

      - name: Build
        run: yarn build

  ci-api:
    name: Run CI for the Node API application
    defaults:
      run:
        working-directory: ./src/api
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: yarn install
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Test with coverage
        run: yarn test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: api-coverage
          path: ./src/api/coverage/

  ci-sonar:
    name: Perform Sonar analysis
    runs-on: ubuntu-latest
    needs: [ci-client, ci-api]
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Get current version
        id: version
        run: |
          echo "value=$(npm pkg get version --workspaces=false | tr -d \")" >> "$GITHUB_OUTPUT"

      - name: Get current commit
        id: commit
        run: |
          echo "value=$(echo ${{ github.sha }} | sed 's/\(.\{7\}\).*/\1/')" >> "$GITHUB_OUTPUT"

      - name: Download client coverage
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: client-coverage
          path: ./src/client/coverage/

      - name: Download API coverage
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: api-coverage
          path: ./src/api/coverage/

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectVersion=${{ steps.version.outputs.value }}-${{ steps.commit.outputs.value }}
